---
- name: Spotify OAuth Authentication
  hosts: localhost
  gather_facts: no
  vars:
    client_id: "your_spotify_client_id"
    client_secret: "your_spotify_client_secret"
    redirect_uri: "your_redirect_uri"
    auth_url: "https://accounts.spotify.com/authorize"
    token_url: "https://accounts.spotify.com/api/token"
    scope: "playlist-modify-public"
    auth_code: ""

  tasks:
    - name: Obtain authorization code URL
      uri:
        url: "{{ auth_url }}"
        method: GET
        return_content: yes
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        body_format: form-urlencoded
        body:
          client_id: "{{ client_id }}"
          response_type: "code"
          redirect_uri: "{{ redirect_uri }}"
          scope: "{{ scope }}"
      register: auth_response

    - debug:
        msg: "Please open the following URL in your browser and authorize the application: {{ auth_response.url }}"

    - name: Pause to enter the authorization code
      pause:
        prompt: "Enter the authorization code you received after authorizing the application"
      register: pause_result

    - set_fact:
        auth_code: "{{ pause_result.user_input }}"

    - name: Exchange authorization code for access token
      uri:
        url: "{{ token_url }}"
        method: POST
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        body_format: form-urlencoded
        body:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          grant_type: "authorization_code"
          code: "{{ auth_code }}"
          redirect_uri: "{{ redirect_uri }}"
      register: token_response

    - debug:
        msg: "Access token: {{ token_response.json.access_token }}"
